require 'fluentnode'
helpers = require('./global-setup')
electron_Prebuild = require('electron-prebuilt')
appPath = __dirname.path_Combine('../../electron-apps/web-view')
Application = require('spectron').Application
assert = require('assert')

describe 'application launch 4', ->
  @timeout 10000
  app = null
  path = [ appPath ]
  beforeEach (done) ->
    helpers.setupTimeout this
    helpers.startApplication(args: path).then (startedApp) ->
      app = startedApp
      done()
      return
  afterEach ->
    helpers.stopApplication app
  afterEach ->
#if (this.app && this.app.isRunning()) {
#    return this.app.stop()
#}
    return
    
  it 'shows an initial window abc', ->
    app.isRunning().assert_Is_True()
    app.client.getWindowCount().then (count) ->
      assert.equal count, 3
      return
  return

# ---
# generated by js2coffee 2.2.0